export const HEADER_ENTRY_DELAY_MS = 2000
export const CARD_ENTRY_START_DELAY_MS = HEADER_ENTRY_DELAY_MS + 950
export const HEADER_SUBTITLE_STAGGER_MS = 250
export const HEADER_TITLE_DURATION_MS = 800
export const HEADER_SUBTITLE_DURATION_MS = 700

export const GALLERY_PAGE_FADE_DURATION_S = 0.18
export const GALLERY_CARD_ENTRY_DURATION_S = 0.5
export const GALLERY_CARD_REENTER_DURATION_S = 0.32
export const GALLERY_CARD_STAGGER_S = 0.15

export const PROGRESS_BAR_ENTRY_DURATION_S = 0.65
export const PROGRESS_BAR_UPDATE_DURATION_S = 0.26
export const PROGRESS_BAR_TRACK_DURATION_S = 0.24
export const PROGRESS_LABEL_ENTRY_DURATION_S = 0.35
export const PROGRESS_LABEL_STAGGER_S = 0.08

export const FOCUS_EXIT_MS = 600
export const FOCUS_BACKDROP_FADE_S = 0.2
export const WHEEL_NAV_THRESHOLD = 30

export const GALLERY_CARD_WIDTH = 252
export const GALLERY_CARD_HEIGHT = 368

export const FOCUS_PANEL_MAX_WIDTH = 540
export const FOCUS_PANEL_MAX_HEIGHT = 780
